# Chemical Data: Structured Data

In [13]:
import pandas as pd

In [37]:
X = pd.read_csv('../data/molorg_features.csv',header = 0)
print X.shape
X.head(n=10)

 (1000, 700)

,MW,AMW,Sv,Se,Sp,Si,Mv,Me,Mp,Mi,...,SpMAD_B(p),Ho_B(p),EE_B(p),SM1_B(p),SM2_B(p),SM3_B(p),SM4_B(p),SM5_B(p),SM6_B(p),VE1_B(p)
0,264.37,8.528,21.864,30.698,23.466,33.993,0.705,0.990,0.757,1.097,...,1.645,12.498,5.172,2.991,4.388,5.295,6.526,7.661,8.897,3.875
1,369.62,11.551,24.107,32.222,27.301,34.756,0.753,1.007,0.853,1.086,...,1.578,14.365,5.365,3.183,4.519,5.487,6.719,7.923,9.188,3.727
2,338.52,8.257,27.830,40.433,30.603,44.786,0.679,0.986,0.746,1.092,...,1.593,14.872,5.359,3.209,4.561,5.481,6.700,7.846,9.080,4.076
3,365.48,8.702,30.412,41.683,32.233,45.906,0.724,0.992,0.767,1.093,...,1.684,17.885,5.581,3.315,4.770,5.688,6.957,8.123,9.397,4.371
4,285.54,7.932,22.324,35.283,25.801,39.995,0.620,0.980,0.717,1.111,...,1.443,10.886,4.991,2.974,4.183,5.118,6.279,7.431,8.641,2.983
5,262.38,8.199,20.423,32.222,21.728,36.571,0.638,1.007,0.679,1.143,...,1.539,11.329,4.975,2.856,4.227,5.077,6.279,7.388,8.596,3.710
6,326.36,8.368,27.832,39.167,28.693,42.535,0.714,1.004,0.736,1.091,...,1.664,17.229,5.475,3.193,4.679,5.564,6.843,8.014,9.292,4.038
7,303.53,7.403,25.664,40.091,28.915,45.490,0.626,0.978,0.705,1.110,...,1.500,13.149,5.198,3.087,4.380,5.317,6.511,7.691,8.932,3.530
8,232.36,6.280,21.499,36.483,23.319,41.943,0.581,0.986,0.630,1.134,...,1.469,10.295,4.848,2.816,4.101,4.944,6.112,7.204,8.395,3.263
9,297.44,6.610,27.047,44.469,29.086,50.856,0.601,0.988,0.646,1.130,...,1.518,13.698,5.156,3.060,4.399,5.249,6.442,7.559,8.777,3.783

In [15]:
y = pd.read_csv('../data/molorg_pol.csv', header = 0)
print y.shape
y.head(n=10)

(1000, 1)

   pol_Bohr3
0   198.6203
1   240.7911
2   242.9596
3   274.1072
4   185.0798
5   161.2420
6   235.3045
7   200.4527
8   154.2377
9   213.7634

# check for missing data

In [23]:
print X.isna().any().sum()
print y.isna().any().sum()
# available options to replace or remove missing data
# pandas: fillna/dropna
# sklearn: imputer

0
0

# check for constant columns

In [36]:
pre_columns = X.columns
X = X.loc[:, (X != X.iloc[0]).any()]
print X.shape
print 'removed columns: ', [i for i in pre_columns if i not in X.columns]

(1000, 699)
removed column:

IndexError: list index out of range

In [25]:
Xy = pd.concat([X,y], axis = 1)
print Xy.shape

(1000, 701)

In [26]:
Xy_corr = Xy.corr(method='pearson')

In [27]:
Xy_corr[y.columns[0]].sort_values(ascending=False).head(n = 10)

pol_Bohr3     1.000000
SpPos_B(p)    0.963040
Wi_B(p)       0.962894
HyWi_B(p)     0.957987
Ho_B(m)       0.953821
SpPos_B(v)    0.953416
Wi_B(v)       0.953205
SpAbs_B(m)    0.952317
Ho_B(p)       0.951189
SM1_B(p)      0.951043
Name: pol_Bohr3, dtype: float64

In [28]:
Xy_corr[y.columns[0]].sort_values(ascending=False).tail(n = 10)

GD          -0.891986
SpMaxA_X    -0.894276
SpMaxA_A    -0.895247
WiA_H2      -0.895354
SpMaxA_L    -0.896842
SpMaxA_H2   -0.897110
Xt          -0.898552
VE2_L       -0.908247
VE2sign_L   -0.908247
Psi_i_1s          NaN
Name: pol_Bohr3, dtype: float64

In [30]:
X['Psi_i_1s']

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
5      0.0
6      0.0
7      0.0
8      0.0
9      0.0
10     0.0
11     0.0
12     0.0
13     0.0
14     0.0
15     0.0
16     0.0
17     0.0
18     0.0
19     0.0
20     0.0
21     0.0
22     0.0
23     0.0
24     0.0
25     0.0
26     0.0
27     0.0
28     0.0
29     0.0
      ...
970    0.0
971    0.0
972    0.0
973    0.0
974    0.0
975    0.0
976    0.0
977    0.0
978    0.0
979    0.0
980    0.0
981    0.0
982    0.0
983    0.0
984    0.0
985    0.0
986    0.0
987    0.0
988    0.0
989    0.0
990    0.0
991    0.0
992    0.0
993    0.0
994    0.0
995    0.0
996    0.0
997    0.0
998    0.0
999    0.0
Name: Psi_i_1s, Length: 1000, dtype: float64